### ISSUE TITLE
flicker problem

### ISSUE THREAD

**Issue by vipcode** [elgransan/BlazorReorder#9]
Hi,
thanks a lot for your work with blazorreorder everything works perfect except a flickering if the elements heights differ (jumping up and down) any suggestions how to fix this?
With best regards
Vipcode

**Comment by elgransan** [comment]
Hi, I couldn't reproduce the error can you give me some example?

**Comment by vipcode** [comment]
> Hi, I couldn't reproduce the error can you give me some example?

hi yes sure try this in index.razor

```
<div class="card" style="width:200px;">
    <Reorder Items="list" TItem="ListItem">
        <div class="mb-2 mx-2">
            <h5>@context.title</h5>
            <p>@context.details <a href="@context.url">Go</a></p>      
        </div>
    </Reorder>
</div>


@code
{
    public List<ListItem> list = new()
    {
        new ListItem("Google", "https://google.com", "Again looking for a bugAgain looking for a bug Again looking for a bug Again looking for a bugAgain looking for a bugAgain looking for a bug..."),
        new ListItem("StackOverflow", "https://stackoverflow.com", "Could be this the solution?"),
        new ListItem("GitHub", "https://github.com", "Let's get awesome code"),
        new ListItem("Twitter", "https://twitter.com", "I want to rest"),
        new ListItem("Another", "https://another.com", "The solution must be somewhere!!!")
    };
}
```


now try to drag e.g. stackoverflow over google to see the flickering

**Comment by elgransan** [comment]
Ok, I could reproduce it now, I understood the problem, and I think I know the solution ... let me do some tests. Thanks

**Comment by elgransan** [comment]
I've uploaded a new release solving this issue.

**Comment by vipcode** [comment]
thanks a lot elgransan for your time and effort. works perfect now
how can i buy you a coffee

**Comment by elgransan** [comment]
Glad to help! No needs to coffee I already had breakfast :)
